services:
  yt2mp3:
    build: .
    image : dragsnake/cmasf:yt2mp3
    networks:
      - front-tier
      - back-tier
    ports:
      - "5052:5052"
    environment:
      REDIS : "redis://cmasf-redis"
    external_links:
      - cmasf-redis
    container_name: yt2mp3
    restart: unless-stopped
    volumes:
      - /home/egor/flask/mp3:/app/static/mp3

networks:
  back-tier:
    name: cmasf_bot_back-tier
    external: true
  front-tier:
    driver: bridge